helloworld:
	./bdfconv -v -f 1 -m '0-127,6016-6121,57344-57413' NotoSansKhmer-Light_6x9.bdf -o notosans_6x9.h -n notosans_6x9 -d NotoSansKhmer-Light_6x9.bdf
	./bdfconv -v -f 1 -m '0-127,6016-6121,57344-57413' NotoSansKhmer-Light_6x8.bdf -o notosans_6x8.h -n notosans_6x8 -d NotoSansKhmer-Light_6x8.bdf