helloworld:
	./bdfconv -v -f 1 -m '0-127,6016-6121,57344-57444' NotoSans_6x9.bdf -o notosans_6x9.c -n notosans_6x9 -d NotoSans_6x9.bdf
	./bdfconv -v -f 1 -m '0-127,6016-6121,57344-57444' NotoSans_6x8.bdf -o notosans_6x8.c -n notosans_6x8 -d NotoSans_6x8.bdf